### ISSUE TITLE
add_employee

### ISSUE THREAD

**Issue by Incalenn** [HuitingFENG/project-testing-team-i#4]

**Comment by Incalenn** [comment]
Test Name : Zip Code Testing
Result : Negative
Explanation : We wanted to see if we could put an unlimited amount of numbers in the Zip Code field, naturally there isn't a Zip Code on Earth that is such as : 11111111111111111111111111111111111111111. Adding this Zip Code provoked a Server Error (500).

**Comment by Incalenn** [comment]
Test Name : Address Field's correct syntax
Result : Negative
Explanation : We wanted to make sure that the addresses that were being typed in were correct. The thing is that whenever we want to add an address that is solely made of integers, it would work, such as : 77777777. Which is irrelevant since it is not a real address.

**Comment by SwevenNeith** [comment]
Test Name: Adding Void Employee
Result: Positive
Explanation: We cannot add a new employee if all the fields of the form are empty

**Comment by SwevenNeith** [comment]
Test Name: Name's Field Correct Syntax
Result: Negative
Explanation: We can add an employee that has a number as name. Which is irrelevant since it is not a real name

**Comment by SwevenNeith** [comment]
Test Name: City and ZIP Code Difference
Result: Negative
Explanation: When we enter the city (for example Paris), we can enter a ZIP code that doesn't correspond to Paris (like 78600). Which shouldn't be possible.

**Comment by Incalenn** [comment]
Test Name : Hiring Contract date
Result : Negative
Explanation : The test is negative since we gave it a hiring contract which starts in 3001, by this time, I would have the time to rebirth atleast 10 times if not more. In terms of data consistency and sense, it is wrong.

**Comment by HuitingFENG** [comment]
retransfer to different issues' discrption
